exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

encoding: utf-8

lang: en-IN

title: "QuoteRoller"

remote_theme: jekyll-theme-alembic
